#include "sha-256.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include <string.h>
#include <limits.h>
#include <errno.h>

#define H_LEN 8
#define K_LEN 64
#define BLOCK_SIZE_BYTES 64
#define ROUNDS 64
#define WORDS_LENGTH 16
#define EXPANDED_WORDS_LENGTH 64
#define UINT32_BITS 32
#define BYTE_IN_BITS 8

static void convertInBigEndian(uint32_t *block)
{
    for (size_t i = 0; i < 16; i++)
    {
        if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
        {
            block[i] = __builtin_bswap32(block[i]); /** @todo: Fix portability  */
        }
    }
}

/**
 * @brief Set as 1 the first bit after the end of the message and the size at the end of the last block.
 *
 * @param block block to be padded
 * @param messageSize the length of the input
 * @param paddedSize the lenght of the padded message - after the calculation.
 *
 * @note The size, in the padding operation, is represented by a 64bit integer.
 */
static void padding(uint8_t *block, size_t messageSize, size_t paddedSize)
{
    block[messageSize] = 0x80;

    size_t l = messageSize * 8;

    block[paddedSize - 1] = (uint8_t)(l & 0xFF);
    block[paddedSize - 2] = (uint8_t)((l & 0xFF00) >> BYTE_IN_BITS);
    block[paddedSize - 3] = (uint8_t)((l & 0xFF0000) >> (BYTE_IN_BITS * 2));
    block[paddedSize - 4] = (uint8_t)((l & 0xFF000000) >> (BYTE_IN_BITS * 3));
    block[paddedSize - 5] = (uint8_t)((l & 0xFF00000000) >> (BYTE_IN_BITS * 4));
    block[paddedSize - 6] = (uint8_t)((l & 0xFF0000000000) >> (BYTE_IN_BITS * 5));
    block[paddedSize - 7] = (uint8_t)((l & 0xFF000000000000) >> (BYTE_IN_BITS * 6));
    block[paddedSize - 8] = (uint8_t)((l & 0xFF00000000000000) >> (BYTE_IN_BITS * 7));
}

/**
 * @brief Right Rotation
 *
 * @param p Prime number
 * @param x Rotation
 *
 * @note defining a macro doesn't seem the right choice.
 *
 * In assembly:
 * ```asm
 *       cmp     DWORD PTR [rbp-4], 0
 *       sete    al
 *       movzx   edx, al
 *       mov     eax, 32
 *       sub     eax, DWORD PTR [rbp-4]
 *       mov     esi, 1
 *       mov     ecx, eax
 *       sal     esi, cl
 *       mov     eax, esi
 *       or      eax, edx
 *       mov     DWORD PTR [rbp-4], eax
 * ```
 * instead a inline function
 * ```asm
 *       mov     esi, eax
 *       xor     eax, eax
 *       ror     esi, 5
 * ```
 */
static inline uint32_t rotr(uint32_t p, uint32_t x)
{
    return ((x >> p) | (x << (UINT32_BITS - p)));
}

/**
 * @brief: Right Shift
 *
 * @param p Prime number
 * @param x Shift
 */
static inline uint32_t shr(uint32_t p, uint32_t x)
{
    return (x >> p);
}

/**
 * @brief sigma0 function in SHA256.
 *
 * @param x Value
 *
 * $ \sigma_0(x) = \mathrm{ROTR}^7(x) \oplus \mathrm{ROTR}^{18}(x) \oplus \mathrm{SHR}^3(x) $
 */
static inline uint32_t sigma0(uint32_t x)
{
    return (rotr(7, x) ^ rotr(18, x) ^ shr(3, x));
}

/**
 * @brief sigma1 function in SHA256.
 *
 * @param x Value
 *
 * $ \sigma_1(x) = \mathrm{ROTR}^{17}(x) \oplus \mathrm{ROTR}^{19}(x) \oplus \mathrm{SHR}^{10}(x) $
 */
static inline uint32_t sigma1(uint32_t x)
{
    return (rotr(17, x) ^ rotr(19, x) ^ shr(10, x));
}

/**
 * @brief Sigma0 function in SHA256.
 *
 * @param x Value
 *
 * $ \Sigma_0(x) = \mathrm{ROTR}^2(x) \oplus \mathrm{ROTR}^{13}(x) \oplus \mathrm{ROTR}^{22}(x) $
 */
static inline uint32_t Sigma0(uint32_t x)
{
    return (rotr(2, x) ^ rotr(13, x) ^ rotr(22, x));
}

/**
 * @brief Sigma1 function in SHA256.
 *
 * @param x Value
 *
 * $ \Sigma_1(x) = \mathrm{ROTR}^6(x) \oplus \mathrm{ROTR}^{11}(x) \oplus \mathrm{ROTR}^{25}(x) $
 */
static inline uint32_t Sigma1(uint32_t x)
{
    return (rotr(6, x) ^ rotr(11, x) ^ rotr(25, x));
}

/**
 * @brief Choose function in SHA256.
 *
 * @param e 5th local variable in the round
 * @param f 6th
 * @param g 7th
 *
 * $ \mathrm{Ch}(e,f,g) = (e \land f) \oplus (\neg e \land g) $
 */
static inline uint32_t choose(uint32_t e, uint32_t f, uint32_t g)
{
    return ((e & f) ^ (~e & g));
}

/**
 * @brief Maj function in SHA256.
 *
 * @param a 1th local variable in the round
 * @param b 2th
 * @param c 3th
 *
 * $ \mathrm{Maj}(a,b,c) = (a \land b) \oplus (a \land c) \oplus (b \land c) $
 */
static inline uint32_t maj(uint32_t a, uint32_t b, uint32_t c)
{
    return ((a & b) ^ (a & c) ^ (b & c));
}

/**
 * @brief Generate Words for a block
 *
 * Copy the first 16 words from the current block.
 * After the 16th:
 *
 * $W[i] = W[i-16] + σ0(W[i-15]) + W[i-7] + σ1(W[i-2])$
 */
static void generateWords(uint32_t *dest, uint8_t *src)
{
    memcpy(dest, src, BLOCK_SIZE_BYTES);
    convertInBigEndian(dest);

    for (size_t i = WORDS_LENGTH; i < EXPANDED_WORDS_LENGTH; i++)
    {
        dest[i] = dest[i - 16] + sigma0(dest[i - 15]) + dest[i - 7] + sigma1(dest[i - 2]);
    }
}

/**
 * @brief Compression round of SHA256 (The iterations are 64)
 *
 * @param H constants - generated by first 8 primes
 * @param K costants - generated by first 64 primes
 *
 * @param expandedWords the expaded 64 words from 16 words block (512 bit)
 *
 * @note
 */
static void compressionRounds(uint32_t *H, uint32_t *K, uint32_t *expandedWords)
{
    uint32_t a = H[0];
    uint32_t b = H[1];
    uint32_t c = H[2];
    uint32_t d = H[3];
    uint32_t e = H[4];
    uint32_t f = H[5];
    uint32_t g = H[6];
    uint32_t h = H[7];

    for (size_t i = 0; i < ROUNDS; i++)
    {
        /**
         * $T1 = h + Σ1(e) + Ch(e,f,g) + K[i] + W[i]$
         * $T2 = Σ0(a) + Maj(a,b,c)$
         */

        uint32_t T1 = h + Sigma1(e) + choose(e, f, g) + K[i] + expandedWords[i];
        uint32_t T2 = Sigma0(a) + maj(a, b, c);

        h = g;
        g = f;
        f = e;
        e = d + T1;
        d = c;
        c = b;
        b = a;
        a = T1 + T2;
    }

    H[0] += a;
    H[1] += b;
    H[2] += c;
    H[3] += d;
    H[4] += e;
    H[5] += f;
    H[6] += g;
    H[7] += h;
}

/**
 * @note taken from https://github.com/Moridi/SHA-256/blob/master/sha256.cpp
 */
static uint32_t HBluePrint[H_LEN] = {0x6a09e667,
                                     0xbb67ae85,
                                     0x3c6ef372,
                                     0xa54ff53a,
                                     0x510e527f,
                                     0x9b05688c,
                                     0x1f83d9ab,
                                     0x5be0cd19};

static uint32_t KBluePrint[K_LEN] = {0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
                                     0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
                                     0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
                                     0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
                                     0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
                                     0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
                                     0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
                                     0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
                                     0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
                                     0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
                                     0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
                                     0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
                                     0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
                                     0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
                                     0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
                                     0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2};

/**
 * @brief Init Costants H and K in the `sha256` algorithm
 * 
 * @param H constants array
 * @param K constants array
 */
static void initConstants(uint32_t *H, uint32_t *K)
{
    memcpy(H, HBluePrint, H_LEN * 4);
    memcpy(K, KBluePrint, K_LEN * 4);
}

/**
 * @brief Sha-256 algorithm.
 *
 * @param msg input data
 * @param messageSize size of the input data
 * @param digest the result. It's an array of `uint32_t`, with length 8
 *
 * @return 1 if an error occurs,
 * 0 if everything is ok.
 *
 * @note Set `errno` to `ENOMEM` if there's an allocation issue
 *
 */
int sha256(const uint8_t *msg, size_t messageSize, uint32_t *digest)
{
    uint32_t H[H_LEN];
    uint32_t K[K_LEN];

    initConstants(H, K);

    /** +9 = 1 byte (0x80 padding bit) + 8 bytes (64-bit message length) */
    size_t nOfBlocks = (size_t)ceil((double)(messageSize + 9) / (double)BLOCK_SIZE_BYTES);
    size_t paddedSize = nOfBlocks * BLOCK_SIZE_BYTES;

    uint8_t *data = (uint8_t *)malloc(paddedSize);
    /** Set to zero to ensure clean data, and for the next padding operations */
    memset(data, 0, paddedSize);

    if (!data)
    {
        errno = ENOMEM;
        return 1;
    }

    memcpy(data, msg, messageSize);
    padding(data, messageSize, paddedSize);

    uint32_t words[EXPANDED_WORDS_LENGTH] = {0};

    for (size_t i = 0; i < nOfBlocks; i++)
    {
        /** 64 words of 32-bit: first 16 copied, remaining 48 generated */
        generateWords(words, data+(i*BLOCK_SIZE_BYTES));
        compressionRounds(H, K, words);
    }

    memcpy(digest, H, H_LEN * 4);

    free(data);
    return 0;
}

/**
 * @brief Convert the digest of Sha256 from uint32_t array in string - with length 64 (i.e. DGST_LENGTH)
 *
 * @param digest the digest
 * @param dest destination string
 */
void digestToString(const uint32_t *digest, char *dest)
{
    for (size_t i = 0; i < 8; i++)
    {
        sprintf(dest + i * 8, "%08x", digest[i]);
    }
}

